### PR TITLE
✨ Detect current git branch for watch command

### PR DESCRIPTION
**Pull request by marcotc**
This PR makes `circleci-cli watch` use the current git branch (if present) as the default `--branch` argument.

### CODE REVIEW

**Comment by marcotc** [comment]
This is my first contribution, so please let me know if there's any additional requirements I might have overlooked.

As a side note, I tried to update the documentation for the Thor command, to reflect this new default value, but my only option would be to actually provide the early resolved `branch_name`, which is not what I'm looking for: I just wanted to document that the default is the current branch.

Also, I noticed that `circleci-cli builds` could use the same treatment, but I wanted to keep this PR short, and also I'd have to come up with a mechanism to allow for `circleci-cli builds` to still list all builds, as not providing a `--branch` argument would now include the branch filtering. (something like `circleci-cli builds --all-branches`, or `circleci-cli builds --branch ALL`, you can see I couldn't come up with a great suggestion here 😅).

**Comment by marcotc** [comment]
The `rspec` CI failure seems unrelated to my changes. I noticed it was already failing since the last merged PR: https://app.circleci.com/pipelines/github/unhappychoice/circleci-cli/532/workflows/8198c3e1-af93-4d5a-9b26-23cc85c37d1e/jobs/1773

**Comment by unhappychoice** [comment]
Thank you for the PR 🎉 :

> I tried to update the documentation for the Thor command

I just found an  option ↓ and we can use this, can we?
Ref: https://github.com/erikhuda/thor/blob/34df888d721ecaa8cf0cea97d51dc6c388002742/lib/thor.rb#L150

But we have more default values not only the `branch` option, I'll set this by another PR.


> circleci-cli builds could use the same treatment,

`circleci-cli builds --all` / `circleci-cli builds -a` is just enough for me, although there is a conflict when `--branch` and `--all` are specified at the same time.
But I think we can just prioritize either.

And I just notice a bug in existing code, I added a commit https://github.com/unhappychoice/circleci-cli/pull/218/commits/2a9bf45c82295243d12f0365e9cc79274d950507 because I think it's much relevant to this PR.

**Review by unhappychoice — APPROVED** [review]
Anyway,

LGTM

**Comment by unhappychoice** [comment]
@all-contributors please add @marcotc for ideas, code

**Comment by unhappychoice** [comment]
Maybe, I'll release this, #221 and #222 together with major version incremented

**Pull request merged**
